import {
  Activity,
  BarChart3,
  Bot,
  BookOpen,
  Building2,
  Code2,
  CreditCard,
  Gauge,
  Globe2,
  KeyRound,
  List,
  ListTree,
  Radar,
  Settings,
  TerminalSquare,
  Users,
} from "lucide-react";

export const navigationItems = [
  { label: "Home", path: "/", icon: Gauge },
  { label: "Organizations", path: "/organizations", icon: Building2 },
  { label: "Workspaces", path: "/workspaces", icon: Users },
  { label: "Projects", path: "/projects", icon: ListTree },
  { label: "AI", path: "/ai", icon: Bot },
  { label: "API Keys", path: "/api-keys", icon: KeyRound },
  { label: "Usage", path: "/usage", icon: BarChart3 },
  { label: "Billing", path: "/billing", icon: CreditCard },
  { label: "Operations", path: "/operations", icon: Radar },
  { label: "Logs", path: "/logs", icon: List },
  { label: "Webhooks", path: "/webhooks", icon: Globe2 },
  { label: "Developer", path: "/developer", icon: BookOpen },
  { label: "Playground", path: "/developer/playground", icon: TerminalSquare },
  { label: "Team", path: "/team", icon: Code2 },
  { label: "Health", path: "/health", icon: Activity },
  { label: "Settings", path: "/settings", icon: Settings },
];
